language: es
name: example
components:
  db:
    dsn: mysql:host=localhost:3306;dbname=kyubi
    schemaCache: cache
    enableSchemaCache: true
    schemaCacheDuration: 3600
    class: yii\db\Connection
    username: root
    password: root